name: changelog-today

on:
  workflow_dispatch: {}  # run manually from Actions tab

permissions:
  contents: write  # needed to push changes back

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate CHANGELOG for today (frontend/)
        shell: bash
        run: |
          TODAY=$(date +%F)
          {
            echo "# Changelog – $TODAY"
            echo
            git log --since="$TODAY 00:00" --until="$TODAY 23:59:59" \
              --no-merges \
              --pretty="* %s (%h) — %an"
          } > CHANGELOG.md

      - name: Commit changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs(changelog): $(date +%F) updates" || echo "No changes to commit"
          git push
