name: Deploy Frontend to Raspberry Pi

on:
  push:
    paths:
      - 'frontend/**'
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and compile prod artifacts
        run: npm ci && npm run build

      - name: Package artifacts
        run: |
          tar -C out -czf site.tar.gz .
          sha256sum site.tar.gz > site.tar.gz.sha256

      - name: Create Release with assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "deploy-${{ github.sha }}"
          body: "Automated deploy for ${{ github.sha }}"
          files: |
            site.tar.gz
            site.tar.gz.sha256
