name: Deploy Frontend to Raspberry Pi

on:
  push:
    paths:
      - 'frontend/**'
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build && npm run export

      - name: Copy to Raspberry Pi
        run: |
          scp -r out/* pi@YOUR_PI_IP:/var/www/resume-frontend
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
